#!/bin/python3

import base64,lzma,re;exec(lzma.decompress(base64.b64decode(re.sub(r"\.|#|(\r\n|\r|\n)","","""/Td6WFoAAATm1rRGAgAhARYAAA
B0L+Wj4AvKCXVdADKeCM2sldQ8pGjU6x18kuG3yYCeM/SPSaVLAgxaqQYI2jdOa2HEt7R3YGdoNxOAa/KMbxeykwiaIvIV3exemZ//TFWJwNf2kxXLEnQ3rm
W6vNFc0stYtBmdboT7e2D9dxT9g8eMnVjzhU68XGqhYUY4b9vwbKPSXV1QfR5HovK8KmaLgRUp+w2dCznLV/tGu1e0FLU6XW5lniWR4iUxfBLvQ5QGvN49uX
63Jo6zIJim+rC/r4hk18up3zg5daxxNLXewTAngT/zZej7Pi3SNv41d1WJ7khboDIRWB7kkMQqxmc4VziRDjdCRmWUeJtXSTYvlmqVFSrv5wDxE9TAz6L179
3B+1NV3QLDtBjH8v58p6rTT9YUka38HrU7TRysw8KRkgp6aAh7+SOAS/yqa5CEoXHZ7b6XqYS9sqmbmF186Lxyk7nQ5xSbeISDtesaaiKQekEjy4dZl00xM5
LN5HdX8zYYJ2hhT5KjxUQYP07TfVTCOKzR/6+KwSOxlshbMAZPTIJi0pLCFCx600WTB4pAU4+f6fV++jfB1hIJKt4+JhstKdtAR3kDLvsV6N1HF7qYnTL1pj
sEvgFNKOt6adjuyd2pKMvJ3qL7p4b1UJnKfjB4HDORh3Rgd1uUnu8fn1ShZEW0hmRGLGMzRg33qzf38067vp1amqcOwNrATE.4Buyz0GHuowbAr6o8mMMrC6
oWR97ccxlBJ6NOC27eEkMPihxk9...4WiWLVMRmOxB1tmxqVRd3GNBnBN1Od01Nh0aOzGczJ7QSgWOHYi0Li24p4HwR5Y0....L/ZJNjI4CPQiay9BziXPiX
2rIQtXmgl8AhzctZ8jL6On5BxB.4w..5ENZatRHhYc2jjApCMEq3+uGOX6nPuc+/9HQ9XOGxNK6fCUZGPoAQgIvC75+...nCB..96X3Lr02Fc+oZHFdN/gSB
9nSqvhioQFYpgxRSqkKeKKaHc..OE+...Rep6fi2QStNLYlyncO9x6ExiHGV6FzqZjP4/A5EMYob2t19ICwtod1XR...AwpQi8..LOGkq7UhFZZMy7Ez21nT
UjIy0xGd8+3vtAaDOhGy7fDI..TCTIRD..jhExhr2m84OrqGHbCzlT39KFpLaTJf6Ae/x480v8tLsCE54iv7toc...QzN4hFYZ3..LMcALvtWMehAaWJ3Yjm
7asaOA63CqfMIDa3n/llMQU../3dh89HN...efc3MquT96iHdiZpXeQKMKM/PoBhM7AE0tk+szzNM3LuwSJ2n...ZsaJqAMUNIcv.scTxpQ0KGtTrg1u2Qke
vOVpd062hCBXV8AFFVCcWd..85Aeb+lDeVT..zrSfeU9eRTqmTsDOb2WPmBtpPavysJliiCjf0jNzu8L/vS...5UTAnx8UluRsNm..FZ0Va0KyMYs08aqX2C
QMFiTNiSlgMuo+aWWCZS4A.6AyRt7Kms47fy..3jFNOapV0Sn8NgJkIXsYi7zDYONA1PbJaIw9iBGpB4pH..V3w99X2dSkh6el4nk.j8Qym7FChA957HBwRN
5CD8mNV2l/WqZUKmZeD0o..4HTT9Mq81/NO7oX..sb7X/rCHWTtS4s/+0LabCZSW+e5OYOycy1BYK395..BXIajtulOcSjeUHeIqp..Viqrd/YX+yn6fg0iS
dsJK6A/n7d1eMnc0HLg3..cWouNtT1+rjezp0e/..KwbEMpQ4r6........pT3z6nEDKWryfeacHS+H..kVek9LpokyTylZgvU0WQ..NOdkepi7X3Qy0T15l
Q9ATQVVt+7JACWwFXrIk..wNWuXavjheKuEYTsOI..n92BT+oV..VAxfXYM....lk1okV/mb+xsnL7..0BTOO0O8Q9cpz4Pz24xLq0.DvzZETYgMe+dcxeNB
rKZ/8s6xcQ/d2agiPDq/.kxCH1bMwyvutR5Z+iLrCF..YFPQzc2.pYNgxNsHhqB...LyfhmsWbH9i.CCT9Uk1NLGJcNCon3TW/wd5A.R1+ANeqoJXpeHtXom
oQ0yboMdsA3NshuzYpE..18eRnyej+pgPXg7mom+3wa..S0dRfg..F2v1odJN8AMll...RjQf43S.NOSSkzSwPlFDMlUhBXkHQ0EA5..1LS9Rb7OATPBAIvi
etRRIJvdnkEEwvVrXSc..9lZHQX2RoEDTTg0FTRdfkFt..OECDEE..Qq+q11s1K3Azd1...9jct..Y8TtPkOaR+OwCEWevVgTVJROL..noxSNDT9VpbZhyVY
XDPtf/2YeBXwpv6tLCq.F/RsjQSdKXk370e1GutbQe0Sh2../cXfh..5O/Tnn4/QN4Zws8...f..PNJrCGvUUlZJlA96PoACM9Jlqf..VAtz3comP5aqQExL
xrTE3E3Wp2DuXdao+TM.Fe2kPArgwsriWpAZv9ECK8wn8Hs..Fh....9H6w1tJLFO0ooHI6P...dz9HquhE/FTBB3ehm5mCnuguVGF..BLwcv/5uVumpc6n/
M56dFxPAR3LTuWM+Atc.FzN0YuV7dn8lcwnnYpdd2ALrBEZf...PZzSYzvScYM4E+hKIaypSdkOZrQ8kcp3pkdk+e5SWqak1L+KJas..pqtQCbKTc03rv7wP
Izq+Be++qDibpiV535..YSevZ3kpiRBvKmI3r/VxQgFM3o..lypIiMzjFDxXd514BJuD34PD9jGSpHg6ZNJrfHp0jgWjXcAOQpq50f..N43VxtjM6MYgWElm
NHyG3IC1P65zYweNbh..cdkHwc98vhda2yXr2Yoc9knGA..............Pe/l3t3EPE7brr6a3bctlwinF3nD3rAtMgZzr6WPZY3..pbPz9KLa0b0MAsO+
DhLiYx3ah4E2mnmcmo..da6St2NbQc9PP06K5RjWh/HQI7ljYy2sxTAjNqDSO+/6YqTd1MI6FuYItU8eJqXctEYH3vLjF2o4+CEk97..4frg+3M2ekpWB35B
kS5RQ+t59zH1GhNqY0t.RXBpqNz65aQ/L2/zBa/Xg8Ls93Oqshj86H80RC2SNwPJeqGguqRmBKsJeq/knGYX5nGdss8DVNo/Twk0ny.7lTmf7fTrapl3+Q0R
3BZZlkaQGk182qCDymS.gTWE9SB1Rb5W7E3rPCaaLfQ6933xz1spbD78YpblsjsXkObOi9FgEzBGG28BsXgreSuqDJgE1V0IAWOsz..ZuX90HZfCZB4TJH75
llcWvjxTSaUdoDPvI+x.FAcuC+2n/YbOOfr+ZYDGL5EHQeaTF27RJJhU+GcC/Fu0LWxYe1+s6BcHWl/CW0lgORwegEfVQypXgdtCt..rmNkWcflC8t/Y3uoW
hSd4eTuREMx7gboyTPf..gEnNIeMNUi4DZc8VwEiDoSX/Erp2ZVIpc9UEyeAezKSXhe5up8CL50hQlZwgAAAAABM1qkEkjSAOgABk..RPLFwAAmyAKirHEZ/
sCAAAAAARZWg==#####..###############################################################################..##################
####################..##############################################################################.###################
####################..#################..###.......################.....................###########..###################
#####################..########.#...#####..........################...........#####..#############..####################
######################..#########..######..........################...........#####..###########..######################
#######################..#######..#######..........################...........######.#########...#######################
###############..#######..######..#######..........################...........######..#######...........################
###############............#####..#######..........################..........#######..###############..#################
################..##############..########.........################..........#######..#############..###################
#################..##############..#######........##################........########.############...####################
###################..#############.#########.....#####################....##########.##########...######################
#####################...###############################.....#################################...########################
######################..######..#################################################..##..#######..########################
#####################..####..##..#..###########################################.##...###########..######################
#####################.#########.#########################..#########.############################..#####################
####################..############################.####...#.........##############################..####################
####################.#############################.....############################################..###################
###################...#######...####################################################...............#####################
#######################.....####....############################################....####################################
####################################....##################################......########################################
######################################............########################..############################################
#######################################..#########.#########################..##########################################
########################################..###################################..#########################################
##########################################..##################################..########################################
############################################..#################################..#######################################
###########################################...##################################..######################################
##########################################..#####################################..#####################################
########################################...#######################################..####################################
########################################........###################################..###################################
##############################################.####################################..###################################
#############################################..#####################################.###################################
############################################..######################################..##################################
############################################..######################################..##################################
###########################################..########################################.##################################
########################################################################################################################
########################################################################################################################
########################################################################################################################
########################################################################################################################
########################################################################################################################
#################################################################################################################"""))))